Query Exec
neo4j-devtools/relate pull request #217
Opened 2020-10-22 10:36 UTC by akollegger

### Please check if the PR fulfills these requirements
- [ ] The commit message follows our [guidelines](https://github.com/neo4j-devtools/relate/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce?

Bug fixes and small improvements.

### What is the current behavior?

- `relate db:exec <id-or-name>`  only accepts dbms id
- `relate db:exec` does not provide exit code
- `relate db:exec` has extra text which does not enhance the result
- `relate db:exec` would accept cypher files which lacked a terminating `;` but would hang because cypher-shell was waiting for the final `;` from the input stream

### What is the new behavior?

- `relate db:exec <id-or-name>`  accepts either name or dbms id
- `relate db:exec` provides exit code to the shell
- `relate db:exec` has minimal text about success or failure
- `relate db:exec` accepts and executes a single-statement cypher without a terminating `;` by auto-appending a `semicolon` if one was missing

### Does this PR introduce a breaking change?

Possibly. Previous behavior allowed for silent failures which now are caught and reported. Also s

### Other information:

2020-10-23 08:47 UTC, akollegger commented
This is _not_ ready for merge. I've noticed that there is now extra output for every command showing the exit code status.

Jag fixar.

2020-10-23 13:00 UTC, nglgzz commented on packages/cli/bin/run
> +});
This is the reason we were never returning 1 even when throwing an error in the application, right?

2020-10-23 13:00 UTC, nglgzz commented on packages/cli/typings/global.d.ts
> +                      suggestions?: string[];
Is this new in oclif?

2020-10-23 13:00 UTC, nglgzz commented on packages/cli/src/modules/db/exec.module.ts
> +                if (res.search(/unauthorized|Invalid input|Expected param/) !== -1) {
What if instead of parsing the output from Cypher shell we return exactly what we get from it? Both output and return code. I'd prefer to not be parsing output from other tools, unless absolutely necessary.

2020-10-27 12:39 UTC, akollegger commented on e2e/relate fixtures/config/bad-syntax.cypher
> +REURN true;
We could. The e2e tests use `EnvPaths`. Should we extend `EnvPaths` to include a new directory, or use the `tmp` directory? In a "real" environment cypher files would be located in a project. Should we simulate that?

2020-10-27 12:39 UTC, akollegger commented on packages/cli/package.json
> +        "@oclif/errors": "1.3.3",
We do not. And.. explicitly adding the dependency caused problems due to incompatible classes. Removed!

2020-10-27 12:42 UTC, akollegger commented on packages/cli/src/modules/db/exec.module.ts
>                  dbmsId = await readStdin();
Agreed. The args and stdin should be all about the query. The DBMS ID should be a flag, not an arg. 

Something to be shaped later?

2020-10-27 12:45 UTC, akollegger commented on packages/common/src/entities/dbs/dbs.local.ts
> -        const result = await cypherShellCmd(await this.resolveDbmsRootPath(dbmsId), params, from);
Should all functions in this class use `nameOrId`?

2020-10-27 12:47 UTC, akollegger commented on packages/cli/src/modules/db/exec.module.ts
> +                    throw new CLIError('UGH', {exit: 1});
Yes, this was left over from my "shotgun" approach of trying to trace how/where exit codes do/don't happen. Removing.

2020-10-27 12:47 UTC, akollegger commented on packages/cli/typings/global.d.ts
> +                      suggestions?: string[];
I believe so, yes.

2020-10-27 12:51 UTC, akollegger commented on packages/cli/src/modules/db/exec.module.ts
> +                if (res.search(/unauthorized|Invalid input|Expected param/) !== -1) {
That would be more sensible. I was being lazy because the current `exec()` gives no indication about where or not an error has happened. 

Separately, I think we should just send a query and format the result rather than spawning a JVM.

2020-10-27 15:51 UTC, akollegger commented on e2e/relate fixtures/config/bad-syntax.cypher
> +REURN true;
Moved this to creating a project and writing cypher files into it in the `beforeAll()` test setup for the `dbms.e2e.ts` tests.

2020-10-27 15:52 UTC, akollegger commented on packages/cli/bin/run
> +});
Yes, that's right. It needed to be propagated explicitly.

2020-10-27 18:39 UTC, akollegger commented on packages/common/src/entities/dbs/dbs.local.ts
> -        const result = await cypherShellCmd(await this.resolveDbmsRootPath(dbmsId), params, from);
I've changed all of `LocalDBs` to use `nameOrId`. Tests seem ok. Does that _look_ right for intended usage?

2020-10-28 11:46 UTC, huboneo requested changes
Since you havent changed any dependencies I dont see why package-lock should change. Please remove it from the PR

2020-10-28 11:47 UTC, huboneo commented on packages/cli/src/modules/db/exec.module.ts
> +                if (res.search(/unauthorized|Invalid input|Expected param/) !== -1) {
+1 on just upstreaming errors, we should not introduce these kind of dependencies

2020-10-28 11:48 UTC, huboneo commented on packages/common/src/entities/dbs/dbs.local.ts
> -        const result = await cypherShellCmd(await this.resolveDbmsRootPath(dbmsId), params, from);
The philosophy is that all userland methods should accept either

2020-10-29 16:01 UTC, huboneo approved these changes
LGTM

2020-10-30 09:21 UTC, merged